steps:
  - id: "Running tests"
    name: "gcr.io/cloud-builders/go"
    env: ["GOPATH=."]
    args: ["test", "sum"]

  - id: "Building image from Dockerfile"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/codeeducation-k8s-cd:latest"
      - "."