steps:
  - id: "Running tests"
    name: "gcr.io/cloud-builders/go"
    env: ["GOPATH=."]
    args: ["test", "sum"]

  - id: "Building image from Dockerfile.prod"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/codeeducation-k8s-cd:$SHORT_SHA", "-f", "Dockerfile.prod", "."]

  - id: "Pushing image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/codeeducation-k8s-cd:$SHORT_SHA"]

  - id: "Fix deployment file - k8s"
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "/bin/sh"
    args:
      - "-c"
      - |
        sed -i 's#img-app-deployment#gcr.io/$PROJECT_ID/codeeducation-k8s-cd:$SHORT_SHA#g' k8s/deployment.yaml
        cat k8s/deployment.yaml

  - id: "Deploying k8s"
    name: "gcr.io/cloud-builders/kubectl"
    args:
      - "apply"
      - "-f"
      - "k8s/"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-c"
      - "CLOUDSDK_CONTAINER_CLUSTER=cluster-go-sum"