FROM golang:1.14.2 as builder
COPY src /go/src
WORKDIR /go/src/sum
RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-w -s" -o sum

FROM scratch
COPY --from=builder /go/src/sum/sum /
EXPOSE 8000
CMD ["/sum"]