apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-sum
spec:
  selector:
    matchLabels:
      app: go-sum
  template:
    metadata:
      labels:
        app: go-sum
    spec:
      containers:
        - name: go-sum
          image: img-app-deployment
          ports:
            - containerPort: 8000